/* ============================================================
 * en-dict.js — 保研英语面试页内置离线词典(06-16 专用数据源)
 * 覆盖页面所有英文句子的单词：音标 | 释义
 * 点击单词弹窗时使用；查不到原词会自动尝试：
 * 小写 → 去复数s → 去过去式ed → 去ing（含 ing→e）等
 * 供 06_学习工具/16_保研英语面试.html 懒加载,暴露 window.EN_DICT
 * ============================================================ */

window.EN_DICT = {
  "a": "/ə, eɪ/|art. 一（个）",
  "about": "/əˈbaʊt/|prep. 关于",
  "adc": "/ˌeɪ diː ˈsiː/|n. 模数转换器（读电压的芯片）",
  "after": "/ˈæftər/|prep. 在…之后",
  "again": "/əˈɡen/|adv. 再一次",
  "ai": "/ˌeɪ ˈaɪ/|n. 人工智能（Artificial Intelligence）",
  "algorithm": "/ˈælɡərɪðəm/|n. 算法",
  "all": "/ɔːl/|adj. 全部的",
  "also": "/ˈɔːlsoʊ/|adv. 也",
  "am": "/æm/|v. 是（I am 我是）",
  "among": "/əˈmʌŋ/|prep. 在…之中",
  "an": "/ən/|art. 一（个）",
  "and": "/ənd, ænd/|conj. 和",
  "any": "/ˈeni/|adj. 任何的",
  "are": "/ɑːr/|v. 是（you are / we are）",
  "at": "/æt, ət/|prep. 在（某处）",
  "automatic": "/ˌɔːtəˈmætɪk/|adj. 自动的",
  "be": "/biː/|v. 是；成为",
  "because": "/bɪˈkɔːz/|conj. 因为",
  "believe": "/bɪˈliːv/|v. 相信",
  "besides": "/bɪˈsaɪdz/|adv. 另外、此外",
  "big": "/bɪɡ/|adj. 大的",
  "board": "/bɔːrd/|n. 板子；电路板",
  "bring": "/brɪŋ/|v. 带来",
  "brought": "/brɔːt/|v. bring 的过去式，带来",
  "built": "/bɪlt/|v. build 的过去式：建造",
  "but": "/bʌt/|conj. 但是",
  "by": "/baɪ/|prep. 通过；被（step by step 一步步）",
  "can": "/kæn/|v. 能、会",
  "capacitor": "/kəˈpæsɪtər/|n. 电容器",
  "check": "/tʃek/|v. 检查",
  "chip": "/tʃɪp/|n. 芯片",
  "choose": "/tʃuːz/|v. 选择",
  "circuit": "/ˈsɜːrkɪt/|n. 电路",
  "class": "/klɑːs/|n. 课；班级",
  "clean": "/kliːn/|adj. 干净的；（信号）无噪声的",
  "code": "/koʊd/|n. 代码",
  "come": "/kʌm/|v. 来（come true 实现）",
  "computer": "/kəmˈpjuːtər/|n. 计算机",
  "confident": "/ˈkɑːnfɪdənt/|adj. 自信的",
  "contest": "/ˈkɑːntest/|n. 竞赛",
  "control": "/kənˈtroʊl/|n./v. 控制",
  "could": "/kʊd/|v. 能（客气说法）",
  "course": "/kɔːrs/|n. 课程",
  "current": "/ˈkɜːrənt/|n. 电流",
  "datasheet": "/ˈdeɪtəʃiːt/|n. （芯片）数据手册",
  "day": "/deɪ/|n. 天、日",
  "dear": "/dɪr/|adj. 尊敬的（信函称呼）",
  "debug": "/ˌdiːˈbʌɡ/|v. 调试",
  "design": "/dɪˈzaɪn/|n./v. 设计",
  "did": "/dɪd/|v. do 的过去式（用于疑问/否定）",
  "do": "/duː/|v. 做；（助动词）",
  "does": "/dʌz/|v. do 的第三人称（用于疑问）",
  "document": "/ˈdɑːkjumənt/|n. 文档",
  "dream": "/driːm/|n. 梦想",
  "draw": "/drɔː/|v. 画",
  "driver": "/ˈdraɪvər/|n. 驱动程序",
  "drone": "/droʊn/|n. 无人机",
  "effort": "/ˈefət/|n. 努力",
  "electronic": "/ɪˌlekˈtrɑːnɪk/|adj. 电子的",
  "electronics": "/ɪˌlekˈtrɑːnɪks/|n. 电子学",
  "embedded": "/ɪmˈbedɪd/|adj. 嵌入式的",
  "embodied": "/ɪmˈbɑːdid/|adj. 具身的（embodied AI 具身智能）",
  "energy": "/ˈenərdʒi/|n. 能量",
  "engineer": "/ˌendʒɪˈnɪr/|n. 工程师",
  "engineering": "/ˌendʒɪˈnɪrɪŋ/|n. 工程",
  "english": "/ˈɪŋɡlɪʃ/|n. 英语",
  "enjoy": "/ɪnˈdʒɔɪ/|v. 享受、喜欢",
  "esc": "/ˌiː es ˈsiː/|n. 电子调速器（电调）",
  "even": "/ˈiːvn/|adv. 甚至",
  "every": "/ˈevri/|det. 每个（every day 每天）",
  "experiment": "/ɪkˈsperɪmənt/|n. 实验",
  "fan": "/fæn/|n. 范（姓氏）",
  "fast": "/fæst/|adj. 快的",
  "favorite": "/ˈfeɪvərɪt/|adj. 最喜欢的",
  "fft": "/ˌef ef ˈtiː/|n. 快速傅里叶变换（算频谱）",
  "feel": "/fiːl/|v. 感觉、感知",
  "filter": "/ˈfɪltər/|n. 滤波器",
  "firmware": "/ˈfɜːrmwer/|n. 固件",
  "first": "/fɜːrst/|adv./adj. 第一",
  "five": "/faɪv/|num. 五",
  "fifty": "/ˈfɪfti/|num. 五十",
  "fly": "/flaɪ/|v. 飞",
  "for": "/fɔːr/|prep. 为了；给",
  "formation": "/fɔːrˈmeɪʃn/|n. 编队",
  "foundation": "/faʊnˈdeɪʃn/|n. 基础，根基",
  "four": "/fɔːr/|num. 四",
  "free": "/friː/|adj. 空闲的（free time 空闲时间）",
  "frequency": "/ˈfriːkwənsi/|n. 频率",
  "from": "/frʌm/|prep. 来自",
  "fun": "/fʌn/|n. 乐趣",
  "future": "/ˈfjuːtʃər/|n. 未来",
  "give": "/ɡɪv/|v. 给（give up 放弃）",
  "gpa": "/ˌdʒiː piː ˈeɪ/|n. 平均绩点",
  "go": "/ɡoʊ/|v. 去",
  "good": "/ɡʊd/|adj. 好的",
  "graduate": "/ˈɡrædʒuət/|adj./n. 研究生的；毕业生",
  "great": "/ɡreɪt/|adj. 极好的，重大的",
  "hand": "/hænd/|n. 手",
  "hard": "/hɑːrd/|adj. 困难的；努力的",
  "has": "/hʌz/|v. 有（have 的第三人称）",
  "have": "/hæv/|v. 有",
  "help": "/help/|v. 帮助",
  "here": "/hɪr/|adv. 这里",
  "high": "/haɪ/|adj. 高的",
  "hobby": "/ˈhɑːbi/|n. 爱好",
  "honor": "/ˈɑːnər/|n. 荣幸",
  "hope": "/hoʊp/|v. 希望",
  "hubei": "/huːˈbeɪ/|n. 湖北（省份名）",
  "humanoid": "/ˈhjuːmənɔɪd/|adj. 人形的（humanoid robot 人形机器人）",
  "hz": "/hɜːrts/|n. 赫兹（频率单位）",
  "i": "/aɪ/|pron. 我",
  "idea": "/aɪˈdɪə/|n. 想法，主意",
  "in": "/ɪn/|prep. 在…里",
  "interrupt": "/ˌɪntəˈrʌpt/|n. 中断",
  "interview": "/ˈɪntərvjuː/|n. 面试",
  "into": "/ˈɪntuː/|prep. 到…里，变成",
  "introduce": "/ˌɪntrəˈduːs/|v. 介绍",
  "introduction": "/ˌɪntrəˈdʌkʃn/|n. 介绍",
  "is": "/ɪz/|v. 是",
  "it": "/ɪt/|pron. 它",
  "jiahao": "/dʒjɑː ˈhaʊ/|n. 佳豪（人名）",
  "japanese": "/ˌdʒæpəˈniːz/|n. 日语；日本人",
  "job": "/dʒɑːb/|n. 工作",
  "join": "/dʒɔːn/|v. 参加、加入",
  "kinematics": "/ˌkɪnəˈmætɪks/|n. 运动学",
  "know": "/noʊ/|v. 知道",
  "layer": "/ˈleɪər/|n. 层",
  "learn": "/lɜːrn/|v. 学习",
  "let": "/let/|v. 让（Let me… 让我…）",
  "like": "/laɪk/|v. 喜欢",
  "limit": "/ˈlɪmɪt/|v. 限制",
  "line": "/laɪn/|n. 行；线",
  "little": "/ˈlɪtl/|adj. 小的；一点（a little 有点）",
  "lot": "/lɑːt/|n. 许多（a lot of）",
  "love": "/lʌv/|v. 热爱",
  "major": "/ˈmeɪdʒər/|n. 专业；adj. 主要的",
  "made": "/meɪd/|v. make 的过去式：制作",
  "make": "/meɪk/|v. 制作；使",
  "making": "/ˈmeɪkɪŋ/|v. make 的现在分词（制作）",
  "many": "/ˈmeni/|adj. 许多",
  "math": "/mæθ/|n. 数学（口语）",
  "mathematics": "/ˌmæθəˈmætɪks/|n. 数学",
  "mean": "/miːn/|v. 意思是",
  "me": "/miː/|pron. 我（宾格）",
  "mechanical": "/məˈkænɪkl/|adj. 机械的",
  "meet": "/miːt/|v. 遇到",
  "moment": "/ˈmoʊmənt/|n. 片刻（a moment 一会儿）",
  "morning": "/ˈmɔːrnɪŋ/|n. 早上",
  "motion": "/ˈmoʊʃn/|n. 运动",
  "motor": "/ˈmoʊtər/|n. 电机、马达",
  "move": "/muːv/|v. 移动",
  "much": "/mʌtʃ/|adv. 非常（very much）",
  "multi": "/ˈmʌlti/|pref. 多（multi-robot 多机器人）",
  "my": "/maɪ/|pron. 我的",
  "myself": "/maɪˈself/|pron. 我自己",
  "name": "/neɪm/|n. 名字",
  "national": "/ˈnæʃnəl/|adj. 全国的",
  "nervous": "/ˈnɜːrvəs/|adj. 紧张的",
  "new": "/nuː/|adj. 新的",
  "never": "/ˈnevər/|adv. 从不",
  "noise": "/nɔːz/|n. 噪声",
  "no": "/noʊ/|adv. 不、没有",
  "not": "/nɑːt/|adv. 不",
  "now": "/naʊ/|adv. 现在",
  "of": "/əv, ʌv/|prep. …的",
  "on": "/ɑːn/|prep. 在…上",
  "open": "/ˈoʊpən/|adj. 开放的（open source 开源）",
  "opportunity": "/ˌɑːpərˈtuːnəti/|n. 机会",
  "our": "/aʊər/|pron. 我们的",
  "out": "/aʊt/|adv. 出去，在外",
  "outside": "/ˌaʊtˈsaɪd/|prep. 在…之外",
  "own": "/oʊn/|adj. 自己的（my own hands 我自己的手）",
  "paper": "/ˈpeɪpər/|n. 论文",
  "part": "/pɑːrt/|n. 零件；部分",
  "pcb": "/ˌpiː siː ˈbiː/|n. 印刷电路板",
  "people": "/ˈpiːpl/|n. 人们",
  "plan": "/plæn/|n. 计划",
  "please": "/pliːz/|v. 请",
  "port": "/pɔːrt/|n. 端口",
  "power": "/ˈpaʊər/|n. 电源；力量",
  "prize": "/praɪz/|n. 奖、奖项",
  "problem": "/ˈprɑːbləm/|n. 问题",
  "professor": "/prəˈfesər/|n. 教授",
  "program": "/ˈproʊɡræm/|n. 程序",
  "progress": "/ˈprɑːɡres/|n. 进步",
  "project": "/ˈprɑːdʒekt/|n. 项目",
  "province": "/ˈprɑːvɪns/|n. 省",
  "publish": "/ˈpʌblɪʃ/|v. 发表",
  "pwm": "/ˌpiː ˌdʌbljuː ˈem/|n. 脉宽调制（控制电机转速）",
  "question": "/ˈkwestʃən/|n. 问题",
  "rank": "/ræŋk/|v./n. 排名",
  "read": "/riːd/|v. 读",
  "real": "/ˈriːəl/|adj. 真实的",
  "really": "/ˈriːəli/|adv. 真正地，确实",
  "remove": "/rɪˈmuːv/|v. 去除",
  "research": "/rɪˈsɜːrtʃ/|n./v. 研究",
  "resistor": "/rɪˈzɪstər/|n. 电阻器",
  "result": "/rɪˈzʌlt/|n. 结果",
  "robot": "/ˈroʊbɑːt/|n. 机器人",
  "robotics": "/roʊˈbɑːtɪks/|n. 机器人学",
  "ros": "/ˌɑːr oʊ ˈes/|n. 机器人操作系统",
  "run": "/rʌn/|v. 跑；（程序）运行",
  "say": "/seɪ/|v. 说",
  "school": "/skuːl/|n. 学校",
  "science": "/ˈsaɪəns/|n. 科学",
  "schematic": "/skɪˈmætɪk/|n. 原理图",
  "second": "/ˈsekənd/|adj. 第二的",
  "self": "/self/|n. 自己（self-introduction 自我介绍）",
  "sensor": "/ˈsensər/|n. 传感器",
  "serial": "/ˈsɪriəl/|adj. 串行的（serial port 串口）",
  "show": "/ʃoʊ/|v. 显示",
  "signal": "/ˈsɪɡnəl/|n. 信号",
  "simple": "/ˈsɪmpl/|adj. 简单的",
  "simulation": "/ˌsɪmjuˈleɪʃn/|n. 仿真",
  "skill": "/skɪl/|n. 技能，技巧",
  "slowly": "/ˈsloʊli/|adv. 慢慢地",
  "small": "/smɔːl/|adj. 小的",
  "solder": "/ˈsɑːdər/|v./n. 焊接；焊锡",
  "solid": "/ˈsɒlɪd/|adj. 扎实的，可靠的",
  "sorry": "/ˈsɑːri/|adj. 抱歉的",
  "some": "/sʌm/|det. 一些",
  "sometimes": "/ˈsʌmtaɪmz/|adv. 有时",
  "source": "/sɔːrs/|n. 源（open source 开源）",
  "spare": "/speə(r)/|adj. 空闲的，多余的",
  "speak": "/spiːk/|v. 说话",
  "speed": "/spiːd/|n. 速度",
  "spend": "/spend/|v. 花费（时间、钱）",
  "spoken": "/ˈspoʊkən/|adj. 口语的（spoken English 英语口语）",
  "sport": "/spɔːrt/|n. 运动",
  "stable": "/ˈsteɪbl/|adj. 稳定的",
  "start": "/stɑːrt/|v. 开始",
  "step": "/step/|n. 步骤（step by step 一步步）",
  "stm": "/ˌes tiː ˈem/|n. STM32 单片机（32位微控制器）",
  "stm32": "/ˌes tiː ˈem ˈθɜːrti tuː/|n. STM32 单片机（32位微控制器）",
  "store": "/stɔːr/|v. 储存",
  "strength": "/streŋθ/|n. 优点、长处",
  "strengthen": "/ˈstreŋθn/|v. 加强，增强",
  "strong": "/strɔːŋ/|adj. 强的",
  "student": "/ˈstuːdnt/|n. 学生",
  "study": "/ˈstʌdi/|v./n. 学习",
  "sure": "/ʃʊr/|adj. 确信的（I am sure 我确信）",
  "supply": "/səˈplaɪ/|n. 供应（power supply 电源）",
  "system": "/ˈsɪstəm/|n. 系统",
  "talk": "/tɔːk/|v. 谈论",
  "team": "/tiːm/|n. 团队",
  "technology": "/tekˈnɑːlədʒi/|n. 技术",
  "thank": "/θæŋk/|v. 感谢",
  "there": "/ðer/|adv. 那里、在那里",
  "that": "/ðæt/|pron./conj. 那；那个",
  "the": "/ðə, ðiː/|art. 这、那（定冠词）",
  "then": "/ðen/|adv. 然后",
  "thesis": "/ˈθiːsɪs/|n. 学位论文",
  "they": "/ðeɪ/|pron. 他们，它们",
  "thing": "/θɪŋ/|n. 东西、事物",
  "think": "/θɪŋk/|v. 想、思考",
  "this": "/ðɪs/|pron. 这、这个",
  "three": "/θriː/|num. 三",
  "time": "/taɪm/|n. 时间",
  "to": "/tuː, tə/|prep. 到、为了",
  "too": "/tuː/|adv. 太；也",
  "tool": "/tuːl/|n. 工具",
  "top": "/tɒp/|adj. 顶尖的，最高的",
  "true": "/truː/|adj. 真的（come true 实现）",
  "turn": "/tɜːn/|v. 使变成；转动",
  "understand": "/ˌʌndəˈstænd/|v. 理解，懂",
  "university": "/ˌjuːnəˈvɜːrsəti/|n. 大学",
  "update": "/ˌʌpˈdeɪt/|v. 更新",
  "up": "/ʌp/|adv. 向上（give up 放弃）",
  "us": "/ʌs/|pron. 我们（宾格）",
  "use": "/juːz/|v. 使用",
  "useful": "/ˈjuːsfl/|adj. 有用的",
  "very": "/ˈveri/|adv. 非常",
  "volt": "/voʊlt/|n. 伏特（电压单位）",
  "voltage": "/ˈvoʊltɪdʒ/|n. 电压",
  "want": "/wɑːnt/|v. 想要",
  "was": "/wʌz/|v. is 的过去式：是",
  "weakness": "/ˈwiːknəs/|n. 缺点、弱点",
  "website": "/ˈwebsaɪt/|n. 网站",
  "week": "/wiːk/|n. 周、星期",
  "we": "/wiː/|pron. 我们",
  "well": "/wel/|adv. 好",
  "what": "/wʌt/|pron. 什么",
  "when": "/wen/|conj. 当…的时候",
  "which": "/wɪtʃ/|pron. 那个…（引导从句）",
  "why": "/waɪ/|adv. 为什么",
  "will": "/wɪl/|v. 将会",
  "win": "/wɪn/|v. 赢得",
  "with": "/wɪð/|prep. 用；和…一起",
  "word": "/wɜːrd/|n. 单词、词语",
  "work": "/wɜːrk/|v. 运行、起作用；n. 工作",
  "world": "/wɜːrld/|n. 世界",
  "won": "/wʌn/|v. win 的过去式：赢得",
  "would": "/wʊd/|aux. 将，会（假设、委婉）",
  "write": "/raɪt/|v. 写、编写",
  "wrote": "/roʊt/|v. write 的过去式：编写",
  "wuhan": "/wuːˈhæn/|n. 武汉（城市名）",
  "you": "/juː/|pron. 你、你们",
  "your": "/jɔːr/|pron. 你的、你们的",

  /* ===== 扩展：自动控制原理 + 新增高频问答 ===== */
  "actuator": "/ˈæktʃueɪtər/|n. 执行器（如电机）",
  "beautiful": "/ˈbjuːtɪfl/|adj. 美丽的",
  "change": "/tʃeɪndʒ/|v. 改变",
  "closed": "/kloʊzd/|adj. 闭合的（closed loop 闭环）",
  "college": "/ˈkɑːlɪdʒ/|n. 大学、学院",
  "controller": "/kənˈtroʊlər/|n. 控制器",
  "curious": "/ˈkjʊriəs/|adj. 好奇的",
  "damping": "/ˈdæmpɪŋ/|n. 阻尼",
  "degree": "/dɪˈɡriː/|n. 度；学位",
  "derivative": "/dɪˈrɪvətɪv/|adj./n. 微分的；导数",
  "disturbance": "/dɪˈstɜːrbəns/|n. 扰动（外部干扰）",
  "easy": "/ˈiːzi/|adj. 容易的",
  "fail": "/feɪl/|v. 未通过、失败",
  "feedback": "/ˈfiːdbæk/|n. 反馈",
  "finally": "/ˈfaɪnəli/|adv. 最后",
  "find": "/faɪnd/|v. 找到",
  "fix": "/fɪks/|v. 修理、解决",
  "follow": "/ˈfɑːloʊ/|v. 跟随",
  "food": "/fuːd/|n. 食物",
  "friend": "/frend/|n. 朋友",
  "full": "/fʊl/|adj. 充实的；满的",
  "function": "/ˈfʌŋkʃn/|n. 函数",
  "gain": "/ɡeɪn/|n. 增益（放大倍数）",
  "get": "/ɡet/|v. 得到（got 为过去式）",
  "happy": "/ˈhæpi/|adj. 快乐的",
  "hardware": "/ˈhɑːrdwer/|n. 硬件",
  "he": "/hiː/|pron. 他",
  "hello": "/həˈloʊ/|int. 你好（任何时间都适用）",
  "afternoon": "/ˌæftərˈnuːn/|n. 下午",
  "evening": "/ˈiːvnɪŋ/|n. 傍晚、晚上",
  "hometown": "/ˈhoʊmtaʊn/|n. 家乡",
  "honest": "/ˈɑːnɪst/|adj. 诚实的",
  "how": "/haʊ/|adv. 如何、怎样",
  "important": "/ɪmˈpɔːrtnt/|adj. 重要的",
  "integral": "/ˈɪntɪɡrəl/|adj./n. 积分的；积分",
  "interest": "/ˈɪntrəst/|n. 兴趣",
  "interested": "/ˈɪntrəstɪd/|adj. 感兴趣的（be interested in）",
  "laplace": "/ləˈplɑːs/|n. 拉普拉斯（法国数学家）",
  "left": "/left/|adj. 左边的",
  "life": "/laɪf/|n. 生活",
  "loop": "/luːp/|n. 环、回路",
  "machine": "/məˈʃiːn/|n. 机器",
  "maybe": "/ˈmeɪbi/|adv. 也许",
  "model": "/ˈmɑːdl/|n./v. 模型；建模",
  "modeling": "/ˈmɑːdəlɪŋ/|n. 建模",
  "ninety": "/ˈnaɪnti/|num. 九十",
  "oscillation": "/ˌɑːsɪˈleɪʃn/|n. 振荡",
  "overshoot": "/ˌoʊvərˈʃuːt/|n. 超调量",
  "pay": "/peɪ/|v. 值得、有回报（hard work pays 努力有回报）",
  "phd": "/ˌpiː eɪtʃ ˈdiː/|n. 博士学位",
  "phase": "/feɪz/|n. 相位",
  "pid": "/ˌpiː aɪ ˈdiː/|n. PID 控制算法（比例-积分-微分）",
  "pole": "/poʊl/|n. 极点",
  "proportional": "/prəˈpɔːrʃənl/|adj. 比例的",
  "quiet": "/ˈkwaɪət/|adj. 安静的",
  "reach": "/riːtʃ/|v. 到达",
  "reduce": "/rɪˈduːs/|v. 减少",
  "response": "/rɪˈspɑːns/|n. 响应",
  "setpoint": "/ˈsetpɔɪnt/|n. 设定值（目标值）",
  "shake": "/ʃeɪk/|v. 摇晃",
  "side": "/saɪd/|n. 边、侧",
  "smart": "/smɑːrt/|adj. 聪明的",
  "software": "/ˈsɔːftwer/|n. 软件",
  "stable": "/ˈsteɪbl/|adj. 稳定的",
  "stability": "/stəˈbɪləti/|n. 稳定性",
  "state": "/steɪt/|n. 状态",
  "steady": "/ˈstedi/|adj. 平稳的（steady state 稳态）",
  "still": "/stɪl/|adv. 仍然",
  "teach": "/tiːtʃ/|v. 教",
  "them": "/ðem/|pron. 它们、他们",
  "transform": "/ˈtrænsfɔːrm/|n. 变换",
  "transfer": "/ˈtrænsfɜːr/|n./v. 传递（transfer function 传递函数）",
  "try": "/traɪ/|v. 尝试",
  "tune": "/tuːn/|v. 整定、调（参数）",
  "one": "/wʌn/|num. 一；一个人",
  "yes": "/jes/|adv. 是的",
  "keep": "/kiːp/|v. 保持",
  "stay": "/steɪ/|v. 保持",

  /* ===== 补充：不规则变形与特殊词条 ===== */
  "city": "/ˈsɪti/|n. 城市",
  "hardest": "/ˈhɑːrdɪst/|adj. 最难的（hard 的最高级）",
  "found": "/faʊnd/|v. find 的过去式：找到",
  "teamwork": "/ˈtiːmwɜːrk/|n. 团队合作",
  "teammate": "/ˈtiːmmeɪt/|n. 队友",
  "were": "/wɜːr/|v. are 的过去式：是",
  "if": "/ɪf/|conj. 如果、是否",
  "graduation": "/ˌɡrædʒuˈeɪʃn/|n. 毕业",
  "best": "/best/|adj. 最好的（good 的最高级）",
  "smarter": "/ˈsmɑːrtər/|adj. 更聪明的（smart 的比较级）",
  "got": "/ɡɑːt/|v. get 的过去式：得到",
  "p": "/piː/|n. 比例环节（PID 中的 P）",
  "d": "/diː/|n. 微分环节（PID 中的 D）"
};
